### ISSUE TITLE
error running

### ISSUE THREAD

**Issue by kumarnaren** [sanger-bentley-group/GPSC_pipeline_nf#7]
[](url)
![Screenshot 2022-11-21 at 00 42 09](https://user-images.githubusercontent.com/43476233/203060865-f466814a-1008-45d6-95d7-68505fdb69c5.png)

It exited with error shown above,

Also, in order for the clustering to be compatible with previous results, we should use the command:
poppunk_assign --db GPS_v6 --distances GPS_v6/GPS_v6.dists --query <2-column path to assembly> --output <GPSC_assignment> --external-clustering GPS_v6_external_clusters.csv

link for GPS_v6_external_clusters.csv: https://www.pneumogen.net/gps/GPS_v6_external_clusters.csv

**Comment by blue-moon22** [comment]
Hi Narender,
Thanks for testing!
Some quetions:

- Did it run the `download_GPS_ref_db` and `unzip_GPS_ref_db` steps?
- What's the contents of the `gpsTest_manifest.txt`?
- Where did you run it?
- Did the `get_GPSC ` process start? (can you see a cross next to the process?)

**Comment by kumarnaren** [comment]
When I first ran, it had started download database but was taking long time and my laptop was making lot of noises, so I manually downloaded to database using curl, unzipped it, and added it to the said folder. 
I ran the pipeline in GPSC_pipeline_nf folder, I have attached the query file for your references, this file was located in a different folder for which I provided the path: the exact command looked like: nextflow run main.nf --manifest ../gpsTest_manifest.txt --results_dir ../gpsTest
[gpsTest_manifest.txt](https://github.com/sanger-bentley-group/GPSC_pipeline_nf/files/10057431/gpsTest_manifest.txt)

**Comment by kumarnaren** [comment]
also could we have the option to provide the database in a zipped format via an option rather than hard coded "db" folder. So the piepline can do the unzipping and run poppunk

**Comment by blue-moon22** [comment]
Do you have the screenshot above the Error? Unfortunately the Nextflow error message isn't informative so still working it out. (Nextflow's fault, not yours!)

**Comment by kumarnaren** [comment]
I just ran the pipeline again, have shared another screenshot, if this is helpful
![Screenshot 2022-11-21 at 15 26 04](https://user-images.githubusercontent.com/43476233/203093079-9ee347e0-aba9-49a5-a384-31f836541670.png)

**Comment by blue-moon22** [comment]
Okay, that's good. Could you copy and paste here the output of `.command.log` file that is in the directory under Work dir:?

**Comment by kumarnaren** [comment]
here you go:
![Screenshot 2022-11-21 at 15 59 29](https://user-images.githubusercontent.com/43476233/203100964-cc176833-1ea9-4ce1-855c-1f04120bce05.png)

**Comment by blue-moon22** [comment]
Could you try running `./tests/regression_tests.sh` to see how far you get? It will run the command (and uses the manifest `tests/test_manifest.txt`). I think it might be something different about the manifest your supplying, not sure what though.

**Comment by kumarnaren** [comment]
Got it, the problem was due to missing prefix "test_" in the query file I was providing as input. Could you please change that so that there is no prefix required for the query file and also add the external clusters option in the command

**Comment by blue-moon22** [comment]
Possible to supply any manifest filename and shouldn't need a `test_` prefix. The `regression_tests.sh` is an example script that contains the commands and a test

**Comment by blue-moon22** [comment]
Issue was using manifests that include sample ids that are already in the GPS database. This will be flagged in the README in https://github.com/sanger-bentley-group/GPSC_pipeline_nf/pull/8
